### ISSUE TITLE
Schedule TImer Bug

### ISSUE THREAD

**Issue by zhubzy** [zzyzsy0516321/SHHS-App#1]
This is

**Comment by fillna** [comment]
If i exist the app without delete it from backstage, when i enter the app from the task manager, the time remain as the same  as the one i exist before.

**Comment by fillna** [comment]
Horizontal text occupation problem.

**Comment by fillna** [comment]
the database missing period 6

**Comment by zzyzsy0516321** [comment]
Fixed

**Comment by zhubzy** [comment]
FIXED
